# Generated by Django 4.2.23 on 2025-09-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('upload', 'Upload')], max_length=10)),
                ('cnpjs', models.TextField(blank=True, help_text='CNPJs consultados (manual ou lista do arquivo)', null=True)),
                ('arquivo_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('resultado', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=20)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
